import ReduxProvider from "@/components/ReduxProvider/ReduxProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Box, CssBaseline, ThemeProvider } from "@mui/material";
import theme from "@/theme/theme";
// Styles
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CRUD-App",
  description: "Generated by create next app",
  icons: {
    icon: "./assets/imgs/Cart-PNG-Image.png",
  }
};



function RootLayout({ children }: Readonly<{ children: React.ReactNode }>)
{

  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <Header />
              <Box mt="30px">
                {children}
              </Box>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}

export default RootLayout;
